###
# Inventory Manager
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: inventory-manager
  name: inventory-manager
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: inventory-manager
  template:
    metadata:
      labels:
        cluster: management
        component: inventory-manager
    spec:
      containers:
      - name: inventory-manager
        image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/inventory-manager:__NPH_VERSION
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        - "--authxAddress=authx.__NPH_NAMESPACE:8810"
        - "--vpnManagerAddress=vpn-server.__NPH_NAMESPACE:5666"
        - "--managementClusterURL=$(MANAGEMENT_HOST)"
        - "--systemModelAddress=system-model.__NPH_NAMESPACE:8800"
        - "--deviceManagerAddress=device-manager.__NPH_NAMESPACE:6010"
        - "--queueAddress=broker.__NPH_NAMESPACE:6650"
        - "--networkManagerAddress=network-manager.__NPH_NAMESPACE:8000"
        - "--edgeInventoryProxyAddress=edge-inventory-proxy.__NPH_NAMESPACE:5544"
        - "--dnsAddress=$(DNS_HOST)"
        env:
        - name: MANAGEMENT_HOST
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: public_host
        - name: DNS_HOST
          valueFrom:
            configMapKeyRef:
              name: management-config
              key: dns_host
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
